"""empty message

Revision ID: 359a073eaf04
Revises: 9819d9ed71ca
Create Date: 2025-07-27 19:16:36.088705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359a073eaf04'
down_revision = '9819d9ed71ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_registro_general', sa.String(length=100), nullable=False),
    sa.Column('nombre_tradicional', sa.String(length=150), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('referencia_topografica', sa.String(length=150), nullable=True),
    sa.Column('numero_piezas', sa.Integer(), nullable=True),
    sa.Column('fecha_origen', sa.String(length=50), nullable=True),
    sa.Column('fecha_adquisicion', sa.String(length=50), nullable=True),
    sa.Column('procedencia', sa.String(length=150), nullable=True),
    sa.Column('autor', sa.String(length=150), nullable=True),
    sa.Column('aportado_por', sa.String(length=150), nullable=True),
    sa.Column('propietario', sa.String(length=150), nullable=True),
    sa.Column('precio_compra', sa.Float(), nullable=True),
    sa.Column('valoracion_actual', sa.Float(), nullable=True),
    sa.Column('materiales', sa.String(length=250), nullable=True),
    sa.Column('medidas', sa.String(length=150), nullable=True),
    sa.Column('foto', sa.String(length=300), nullable=True),
    sa.Column('estado_general', sa.String(length=150), nullable=True),
    sa.Column('restauraciones', sa.Text(), nullable=True),
    sa.Column('uso_funcion', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('exposiciones', sa.Text(), nullable=True),
    sa.Column('referencias_bibliograficas', sa.Text(), nullable=True),
    sa.Column('prestamos', sa.Text(), nullable=True),
    sa.Column('codigo_qr', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_registro_general')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articulo')
    # ### end Alembic commands ###
