"""empty message

Revision ID: fbd714c5f1da
Revises: 359a073eaf04
Create Date: 2025-07-27 20:15:52.445736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd714c5f1da'
down_revision = '359a073eaf04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulo_nombre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tipo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('articulo_nombre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tipo', ['tipo_id'], ['id'])
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['id'])
        batch_op.create_foreign_key(None, 'articulo_nombre', ['articulo_nombre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('articulo_nombre_id')
        batch_op.drop_column('tipo_id')
        batch_op.drop_column('categoria_id')

    op.drop_table('tipo')
    op.drop_table('categoria')
    op.drop_table('articulo_nombre')
    # ### end Alembic commands ###
